on:
  push:



jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: uv set up
              uses: astral-sh/setup-uv@v5
            - name: テスト実行
              run: |
                uv run fizzbuzz.py